first = input("First name: ").capitalize()
last = input("Last name: ").upper()
email = input("Email address: ").lower()
phone = input("Phone number: ")
title = input("Job Title: ").title()
id = input("ID Number: ")

print("The ID Card is: ")
print("----------------------------------------")
print(f"{last}, {first}")
print(f"{title}")
print(f"ID: {id}")
print()
print(f"{email}")
print(f"{phone}")
print("----------------------------------------")